language: python

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master

# command to install requirements
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then python setup.py install; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install -r requirements3.txt; fi

# command to run tests, e.g. python setup.py test
script:
  - python setup.py test
